#!/usr/bin/env bash
# Install Nginx and the init file have only a message
ADD301_REDIRECT="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=3K8dNctci1Y&list=RD3K8dNctci1Y&start_radio=1 permanent;"
 
sudo apt update -y
sudo apt upgrade -y
sudo apt install nginx -y
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i "30i $ADD301_REDIRECT" /etc/nginx/sites-available/default
sudo service nginx start
