#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
while [ $i -le 8 ]
do 
if [ $i != 8 ]
then
echo "Best School"
if [ $i == 6 ]
then
echo "Hi"
fi
else
echo -n "Best School"
fi
((i++))
done