#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=1
while [ $i -le 10 ]
do 
if [ $i != 10 ]
then
echo "Best School"
if [ $i == 3 ]
then
echo "bad luck"
fi
if [ $i == 8 ]
then
echo "good luck"
fi
else
echo -n "Best School"
fi
i=$(($i+1))
done