#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
i=0
while [ $i -le 9 ]
do 
if [ $i != 9 ]
then
echo "Best School"
if [ $i == 3 ]
then
echo "bad luck"
fi
if [ $i == 7 ]
then
echo "good luck"
fi
else
echo -n "Best School"
fi
i=$(($i+1))
done