#!/usr/bin/env bash
# a Bash script that displays numbers from 1 to 20 
i=1
while [ "$i" -lt 21 ]; do

  # if 4 bad luck elif 8 good luck
  if [ "$i" -eq 4 ]; then
    echo "bad luck from China"
  elif [ "$i" -eq 9 ]; then
    echo "bad luck from Japan"
  elif [ "$i" -eq 17 ]; then
    echo "bad luck from Italy"
  else
    echo $i
  fi

  ((i++))
done